version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - database

  bot:
    build: .
    command: python bot.py
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    env_file:
      - .env
    container_name: database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
