# Generated by Django 5.0 on 2023-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
